# master Branch
-
   branches:
     only:
     - master
   version: 1.1.{build}
   pull_requests:
     do_not_increment_build_number: true
   image: Visual Studio 2015
   shallow_clone: true
   build_script:
   - ps: ./build.ps1
   test: off
   deploy: off

# dev Branch
-
   branches:
    only:
    - dev
   version: 1.1.{build}
   build_script:
   - ps: .\build.ps1 -Target Build
   test: off
   deploy: off