# master Branch
-
   branches:
     only:
     - master
   build_script:
   - ps: ./build.ps1
   test: off
   deploy: off

# dev Branch
-
   branches:
    only:
    - dev
   build_script:
   - ps: .\build.ps1
   test: off
   deploy: off

# catch all
-
   version: 1.1.{build}
   shallow_clone: true
   image: Visual Studio 2015